---
kind: "operation"
client: "rug-cli 0.16.6"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/spring-boot-rest-service"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.3"
executor:
  name: "SetSpringBootParentVersionExecutor"
  group: "atomist-rugs"
  artifact: "spring-boot-editors"
  version: "0.5.2"
  origin:
    repo: "https://github.com/atomist-rugs/spring-boot-editors.git"
    branch: "2e4b222888ddbdee38a88d9d420119b859d0a508"
    sha: "2e4b222"
  parameters:
    - "spring_boot_version": "1.4.4.RELEASE"

---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "NewSpringBootRestService"
  group: "atomist-rugs"
  artifact: "spring-boot-rest-service"
  version: "0.7.1"
  origin:
    repo: "https://github.com/atomist-rugs/spring-boot-rest-service.git"
    branch: "ef752ad5954add0e8ee8626c4fd6134c63aec500"
    sha: "ef752ad"
  parameters:
    - "project_name": "atomist-first-project"
    - "artifact_id": "myartifact"
    - "group_id": "mygroup"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "My new project"
    - "root_package": "com.myorg"
    - "service_class_name": "MyService"

